### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by rizkg** [losalamos/qasm#1]
Hi,
I installed qasm but it does not work, it seems the dwave_sapi2 python module is required. Is it available somewhere ? Is it part of the qOp package from d-wave ? (I have qOp installed already)
Thanks,
Guillaume

**Comment by spakin** [comment]
> I installed qasm but it does not work, it seems the dwave_sapi2 python module is required. Is it available somewhere ? Is it part of the qOp package from d-wave ? (I have qOp installed already)

It's part of SAPI, not qOp.  If you have access to the Qubist interface, go to *Solver API* then *Resource Downloads* then download the appropriate Python Developer Pack for your OS (e.g., `sapi-python-client-2.4-linux64.tar.gz` for Linux).

— Scott

**Comment by rizkg** [comment]
ok, I do not have access to Qubist right now, hopefully soon. I will tell you then if I have more questions,
Thanks for your help,
Guillaume
